### ISSUE TITLE
Crack the Clue - The missing 2 pieces

### ISSUE THREAD

**Issue by sunnyzulu** [oldschoolgg/oldschoolbot#2160] opened 2021-06-22 04:57 UTC
I'm an ironman, and getting the full clue hunter set from crack the clue is not working. I'm not sure if someone has brought it up yet, but because I can't buy it, I thought i'd make a post about it.

**Comment by 6enny6** [comment] 2021-06-22 09:06
dupe of #1696

**Closed by 6enny6** 2021-06-22 09:06 UTC
