### ISSUE TITLE
[OSB] Super Restore wrong error

### ISSUE THREAD

**Issue by Djarcn** [oldschoolgg/oldschoolbot#1730] opened 2021-04-24 17:38 UTC
## 🐛 Bug Report

When attempting to use "+mix super restore" while not having 'Snapdragon Potion (unf)' it gives the response "You don't have enough Red spiders' eggs." rather than "You don't have enough Snapdragon Potion (unf)"
![RedError](https://user-images.githubusercontent.com/30577161/115967760-38ab0780-a4e9-11eb-9b2c-298fa293d896.PNG)

**Comment by osrsolympus** [comment] 2021-04-24 17:39
Duplicate of #1265

**Closed by osrsolympus** 2021-04-24 17:39 UTC
