### ISSUE TITLE
[OSB] Tradable items - dt2 rings/vials of blood

### ISSUE THREAD

**Issue by Lewis7777** [oldschoolgg/oldschoolbot#5330] opened 2023-09-08 16:49 UTC
The desert treasure 2 rings need to be made tradable

the 4x dt2 fully completed rings need to be made tradable items,
Venator ring
Ultor ring
Bellator ring
Magus ring

The graphical appearence of these rings also needs to be updated, as currently they're using the placeholder graphics, below is an example of the venator ring.

Venator ring Current osb/bso graphic = placeholder graphic
https://oldschool.runescape.wiki/w/Ventor_ring_(beta)
It should be this
https://oldschool.runescape.wiki/w/Venator_ring

--

Vials of blood from tob need to be made tradable, especially now considering that scythe is now a global boost.

**Comment by Lewis7777** [comment] 2023-09-08 16:57
> The vestiges aren't tradeable in game, just the finished rings.

O yeah you;re right., I thought I remember selling my vestiges, I must have made them into rings, ty will edit post.

**Comment by LuxrayElite** [comment] 2023-09-08 17:10
Duplicate of #3378, #5284, #5282

**Closed by LuxrayElite** 2023-09-08 17:10 UTC
