### ISSUE TITLE
osb, checkpatch 

### ISSUE THREAD

**Issue by gnmem** [oldschoolgg/oldschoolbot#2115] opened 2021-06-18 20:11 UTC
![osb bug001](https://user-images.githubusercontent.com/78821413/122611642-f681ea80-d081-11eb-89fb-09fb44e5c67a.png)

it says 2 times potato cactus

**Comment by ArtMatters** [comment] 2021-06-18 21:25
Potatoes show up as potato cacti. It's a known bug atm.

**Comment by 6enny6** [comment] 2021-06-18 21:28
dupe of #2080

**Closed by 6enny6** 2021-06-18 21:28 UTC
