### ISSUE TITLE
Lil Lamb Droprate

### ISSUE THREAD

**Issue by wildchickenz** [oldschoolgg/oldschoolbot#1799] opened 2021-05-05 01:45 UTC
Unlike other 'timed' based pets, lil lamb rolls once per 20+ minute instead of 1 roll per minute 

replace this

`if (duration > Time.Minute * 20 && roll(8000)) {
			loot.add('Lil lamb');`

with this, i think

`const minutesInTrip = Math.ceil(duration / Time.Minute);
		for (let i = 0; i < minutesInTrip; i++) {
			if (roll(8_000)) {
				loot.add('Lil Lamb');`

**Comment by osrsolympus** [comment] 2021-05-05 02:42
This is a duplicate of #1740

**Closed by osrsolympus** 2021-05-05 02:42 UTC
