### ISSUE TITLE
Shelldon Spelt Wrong on Receival 

### ISSUE THREAD

**Issue by wildchickenz** [oldschoolgg/oldschoolbot#1583] opened 2021-03-25 01:54 UTC
A crab steals your fish just as you catch it! After some talking, the crab, called Sheldon, decides to join you on your fishing adventures. You can equip Shelldon and he will help you fish!

ez pz fix im sure

**Comment by osrsolympus** [comment] 2021-03-25 01:56
Duplicate of #987

**Closed by osrsolympus** 2021-03-25 01:56 UTC
