### ISSUE TITLE
Clue button for implings

### ISSUE THREAD

**Issue by Hanzigamer** [oldschoolgg/oldschoolbot#4421] opened 2022-09-03 16:45 UTC
Currently there is no button for doing clues after you open impling jars, you would have to @ the bot to get the button. Would it be able to add a clue button for the patreons like there is for other trips? That would be a good qol update.

**Comment by 6enny6** [comment] 2022-09-12 21:42
dupe of #4251

**Closed by 6enny6** 2022-09-12 21:42 UTC
