### ISSUE TITLE
Crystal armour seed buy limit

### ISSUE THREAD

**Issue by borsii** [oldschoolgg/oldschoolbot#5221] opened 2023-07-23 20:14 UTC
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Fix ge buy limit for crystal armour seed. It is currently 1 and it’s 100 in game.

**Comment by LuxrayElite** [comment] 2023-07-24 07:06
Duplicate of #5215

**Closed by LuxrayElite** 2023-07-24 07:06 UTC
