### ISSUE TITLE
Minion went on two trips at once

### ISSUE THREAD

**Issue by BIRDIE13** [oldschoolgg/oldschoolbot#1872] opened 2021-05-15 16:44 UTC
When getting "Say ‍​q to repeat this trip." and then doing =q for a new questing trip, the minion is sent on two trips at the same time.

![afawfawf](https://user-images.githubusercontent.com/37814738/118371570-7281a200-b5ad-11eb-9527-255cb7dc74df.png)
![unknown](https://user-images.githubusercontent.com/37814738/118371572-74e3fc00-b5ad-11eb-842f-567b17b91d6d.png)

**Comment by osrsolympus** [comment] 2021-05-15 16:47
Duplicate of #1797

**Closed by osrsolympus** 2021-05-15 16:47 UTC

**Comment by BIRDIE13** [comment] 2021-05-15 17:24
My bad. Thanks for keeping an eye on me :D
