### ISSUE TITLE
Ring of endurance (uncharged)

### ISSUE THREAD

**Issue by sideshoboob** [oldschoolgg/oldschoolbot#444] opened 2020-07-30 12:09 UTC
## 🐛 Bug Report 

Ring of endurance (uncharged) {bso} shows value in bank but is not able to be traded when sold to the bot. When attempted to equip it stated was not in the bank. When attempted to =sellto said it was not in the bank. We did several attempts but nothing seemed to work. Cheers for the awesome bots

**Comment by jamosaur** [comment] 2020-07-30 12:10
See #420

**Comment by Alexsuperfly** [comment] 2020-07-31 22:52
duplicate of #420

**Closed by Alexsuperfly** 2020-07-31 22:52 UTC
Labels: BSO
