### ISSUE TITLE
Unsired showing loot as purple 

### ISSUE THREAD

**Issue by KyeDon** [oldschoolgg/oldschoolbot#2263] opened 2021-07-02 17:27 UTC
## 🐛 Bug Report

Just got my 2nd unsired, opened it and got an abyssal dagger. This showed in purple like it was a new unique when I also had an abyssal dagger from my first unsired.

![image](https://user-images.githubusercontent.com/47357003/124309731-14ac1800-db63-11eb-8127-b2e1f8f43664.png)

**Comment by KyeDon** [comment] 2021-07-03 13:42
Not sure if this has been fixed but just got another dagger from my 4th unsired and it didn't happen this time. Hopefully helps with troubleshooting.

**Comment by Lilylicious** [comment] 2021-07-18 11:51
This is caused by the bot using a cached image. It doesn't seem to recognize that it can't use a cache when an item shouldn't be purple anymore.

**Comment by kevinsmendes** [comment] 2021-07-29 23:02
Fixed by #2397

**Closed by kevinsmendes** 2021-07-29 23:02 UTC
