### ISSUE TITLE
Minion time to return counting up

### ISSUE THREAD

**Issue by EvolvedBag** [oldschoolgg/oldschoolbot#1325] opened 2021-02-08 13:51 UTC
## 🐛 Bug Report

Been grinding shamans for the past age and a half, last night I sent the minion out with the command I had always used '+m k shaman'. A while later it hadn't returned and I checked it by performing the same command, and it was still out stating it had an hour left. Thought nothing of it and went to bed, logged on this morning and checked again, and it has 14 hours remaining, and waiting a few seconds sees the time go up by however long I waited to check

![image](https://user-images.githubusercontent.com/47138269/107228534-c39c5b80-69ea-11eb-8e82-cc5e1e9151cd.png)
![image](https://user-images.githubusercontent.com/47138269/107228606-d44cd180-69ea-11eb-8271-433f4b46c057.png)

**Comment by JerMous3** [comment] 2021-02-08 13:52
It's a known issue, you have to +cancel the trip and send a new one out.

**Comment by EvolvedBag** [comment] 2021-02-08 13:53
Already done, just wanted to report it if it wasn't known, couldn't find the issue on the forum

**Comment by osrsolympus** [comment] 2021-02-08 15:49
Duplicate of #1324

**Closed** 2021-03-10 02:11 UTC
