### ISSUE TITLE
No trip return message upon farming contract completion

### ISSUE THREAD

**Issue by shelixd** [oldschoolgg/oldschoolbot#2285] opened 2021-07-06 16:45 UTC
When farming something that would complete a farming contract, there is no return message. However the trip is completed since you do get seed packs.

**Comment by mylife212** [comment] 2021-07-07 03:57
Assuming this was caused by the bot-wide bug earlier on OSB which is fixed now. Feel free to re-open if its something else

**Comment by mylife212** [comment] 2021-07-07 04:15
This is a BSO-specific issue, and is possibly related to the engine change. The return message thats an image of Jane's chathead etc. doesn't come back.

**Comment by gc** [comment] 2021-07-11 15:37
Fixed

**Closed by gc** 2021-07-11 15:37 UTC
