### ISSUE TITLE
Boxes not being given at sandy

### ISSUE THREAD

**Issue by baannanna** [oldschoolgg/oldschoolbot#1623] opened 2021-04-01 20:13 UTC
The sand geckos are not giving boxes like they should.
![Discord_PnJnoIespd](https://user-images.githubusercontent.com/79678988/113348854-02180d80-92ec-11eb-9f12-41c70b1fa02a.png)
![Discord_xBscaLPvhW](https://user-images.githubusercontent.com/79678988/113348857-03493a80-92ec-11eb-8b01-7d7c18780dbd.png)

**Comment by osrsolympus** [comment] 2021-04-01 20:19
Duplicate of #1605

**Closed by osrsolympus** 2021-04-01 20:19 UTC
