### ISSUE TITLE
Watermelon planting wrongly

### ISSUE THREAD

**Issue by Vanillaah** [oldschoolgg/oldschoolbot#1115] opened 2020-12-18 09:34 UTC
## 🐛 Bug Report

I had 23 watermelon seeds left and planted with "plant watermelon --ultracompost" after getting a fc medium. 
Then it planted 23x (which shouldn't be possible on it's own) and it only took 23 seeds instead of 69. Also it awarded full exp for planting as if I planted in 23 patches.

![20201218_101501](https://user-images.githubusercontent.com/24986403/102598414-45bf8080-411c-11eb-95b5-92f97269f481.jpg)

**Comment by osrsolympus** [comment] 2020-12-18 10:18
Dupe of https://github.com/oldschoolgg/oldschoolbot/issues/1093#issuecomment-745757185. Niche situation that be resolved in the next update as Andre has coded a fix already.

**Comment by Lajnux** [comment] 2021-01-11 23:35
resolved.

**Closed by Lajnux** 2021-01-11 23:35 UTC
