### ISSUE TITLE
Repeat last combat/skilling session after finishing a clue scroll

### ISSUE THREAD

**Issue by bowiRS** [oldschoolgg/oldschoolbot#4065] opened 2022-06-25 13:18 UTC
When doing combat/fishing/woodcutting you can get clue scrolls and with the latest update, you can click the button to do said clue scroll. It would be nice if the clue completion message had a button to return to the most recent activity.

**Comment by 6enny6** [comment] 2022-06-25 14:15
dupe of #4062

**Closed by 6enny6** 2022-06-25 14:15 UTC
