### ISSUE TITLE
Repetitive/same item in UMB's

### ISSUE THREAD

**Issue by 2Kurrupted** [oldschoolgg/oldschoolbot#1488] opened 2021-03-06 02:53 UTC
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
Im Opening UMBs and receiving a broken set of guthan's legs each time, and each time i receive its not banked.
Im probably sitting at around 5 or 6 umbs opened same broken guthan plateskirt reward and still only one guthans plateskirt in inventory.

**Comment by Craftpure** [comment] 2021-03-06 03:03
This is the issue that Magna posted about in news before going to bed
"There's a visual bug with some of the bank images the bot shows, I'm aware and will fix soon"

**Comment by 2Kurrupted** [comment] 2021-03-06 03:08
Ah, my bad. Thank you i didn't realise

**Comment by Alexsuperfly** [comment] 2021-03-06 03:30
duplicate of #1478

**Closed by Alexsuperfly** 2021-03-06 03:30 UTC
