### ISSUE TITLE
Pickpocketing bug

### ISSUE THREAD

**Issue by 1zzyDeadYet** [oldschoolgg/oldschoolbot#1560] opened 2021-03-19 16:44 UTC
## 🐛 Bug Report

When pickpocketing male ham members, it comes back with female members.
![810ccd7dd5b196ee7c40330303696412](https://user-images.githubusercontent.com/80975673/111814465-dee36c00-88b0-11eb-9225-fce8a4bc9507.png)

**Comment by osrsolympus** [comment] 2021-03-19 16:59
Duplicate of #1549

**Closed by osrsolympus** 2021-03-19 16:59 UTC
