### ISSUE TITLE
BSO Clue Caskets

### ISSUE THREAD

**Issue by Keyzz971** [oldschoolgg/oldschoolbot#527] opened 2020-08-19 14:11 UTC
With the addition of “=open x clue” to BSO it has accidentally removed the chance of getting multiple caskets Worth of loot when you open one, it’s now always one clue = one casket reward

**Comment by Alexsuperfly** [comment] 2020-08-19 15:54
duplicate of #525

**Closed by Alexsuperfly** 2020-08-19 15:54 UTC
