### ISSUE TITLE
Double Quest

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1893] opened 2021-05-20 07:46 UTC
## 🐛 Bug Report

art didn't wanna sign up so I'm doing it for him.

he had the repeat code of `q` and accidently put a = infront of the command so the bot read it as `=q`, and the `q` to repeat.

![image0-1.png](https://user-images.githubusercontent.com/68685674/118939652-87e02e80-b915-11eb-906a-d0738179eb79.png)

**Comment by 6enny6** [comment] 2021-05-20 08:31
duplicate of #1797

**Closed by 6enny6** 2021-05-20 08:31 UTC
