### ISSUE TITLE
Fletching Output

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#1302] opened 2021-02-04 16:03 UTC
## 🐛 Bug Report

Self-explanatory (see below).

![image](https://user-images.githubusercontent.com/21049385/106919946-9729cc00-66d8-11eb-89e5-99a8f1a4f253.png)

**Comment by Alexsuperfly** [comment] 2021-02-10 23:38
duplicate of #1293

**Closed by Alexsuperfly** 2021-02-10 23:38 UTC
