### ISSUE TITLE
Counter for number of mystery boxes opened

### ISSUE THREAD

**Issue by LRB3** [oldschoolgg/oldschoolbot#641] opened 2020-09-16 01:27 UTC
## 🚀 Feature Proposal

If on BSO, if we could have a counter similar to that of clues, like after opening a TMB, it says "you've opened 5 TMBs" or similar etc, with a different one for each type of mystery box

**Comment by Alexsuperfly** [comment] 2020-09-20 13:12
duplicate of #567

**Closed by Alexsuperfly** 2020-09-20 13:12 UTC
Labels: BSO
