### ISSUE TITLE
BSO Special Pets

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#566] opened 2020-08-28 23:17 UTC
## 🚀 Feature Proposal

Add special pets for non xp awarding activities like tanning leather or making logs into planks to incentivize people to do stuff like that for themselves. Also cool paces to implement new pets.

**Comment by kevinsmendes** [comment] 2020-08-28 23:46
Duplicate of #560 Comment there :-)

**Closed** 2020-08-29 00:34 UTC
