### ISSUE TITLE
Pet Zak missing in BSO

### ISSUE THREAD

**Issue by KainoaM** [oldschoolgg/oldschoolbot#621] opened 2020-09-10 14:08 UTC
## 🐛 Bug Report

Got zak pet on bso and it didn’t go into my bank. It is not equipped in any of my gear setups. I tried =b then =b zak.. still won’t show up. I got the drop yesterday night.

**Comment by Alexsuperfly** [comment] 2020-09-10 14:09
were you doing anything else at the time it came back

**Comment by KainoaM** [comment] 2020-09-10 14:11
No. I did do =equippet zak while I had klik equipped already immediately after I got the drop. Maybe that could’ve been the problem.

**Comment by Alexsuperfly** [comment] 2020-09-10 14:15
so you have it equipped then...

**Comment by KainoaM** [comment] 2020-09-10 14:25
No it is not equipped. When I did that it said I didn’t have zak. I checked all my gear setups and it isn’t there. Not in bank either.

**Comment by Alexsuperfly** [comment] 2020-09-10 15:04
after further discussion in discord this was determined to be a duplicate of #585.  improper syncing of user data allowing an update to override the result of a previous command

**Closed by Alexsuperfly** 2020-09-10 15:04 UTC
