### ISSUE TITLE
[BSO] Doug/Mining

### ISSUE THREAD

**Issue by veigarbso** [oldschoolgg/oldschoolbot#656] opened 2020-09-20 12:36 UTC
## 🐛 Bug Report

Mining gold ore with doug I'm not receiving the full amount of ore I mine. 3 Trips in a row I only received 10, 22, then 31 gold ores.
![unknown](https://user-images.githubusercontent.com/71593992/93711429-472cdd00-fb1c-11ea-853b-6cfe7a33b5dc.png)
![f1DCUuO](https://user-images.githubusercontent.com/71593992/93711432-4ac06400-fb1c-11ea-8bf2-8479c4772204.png)
![FXBvGbh](https://user-images.githubusercontent.com/71593992/93711434-4d22be00-fb1c-11ea-8eef-d3ea3acbfcb5.png)

**Comment by Alexsuperfly** [comment] 2020-09-20 13:10
duplicate of #614

**Closed by Alexsuperfly** 2020-09-20 13:10 UTC
Labels: bug
