### ISSUE TITLE
Gearpresets Edit - No longer edits

### ISSUE THREAD

**Issue by WeeGym** [oldschoolgg/oldschoolbot#4435] opened 2022-09-07 09:57 UTC
## 🐛 Bug Report

Since changing to a slash command, the edit feature for gear presets doesn't allow editing 1 piece of gear. 
Previously you could do =GPS update *preset* *gear slot* and it would update the gear accordingly. 
Now when you do the edit, you have to select the slot, then add the gear. 
If you add one change, then the preset will remove all gear except that one item.
This means that any time you try to edit a preset you need to add every single item seperately as it creatiny a new preset

**Comment by TURB042O** [comment] 2022-09-23 19:15
#4411

**Comment by TURB042O** [comment] 2022-09-23 19:19
> ## 🐛 Bug Report
> 
> Since changing to a slash command, the edit feature for gear presets doesn't allow editing 1 piece of gear. 
> Previously you could do =GPS update *preset* *gear slot* and it would update the gear accordingly. 
> Now when you do the edit, you have to select the slot, then add the gear. 
> If you add one change, then the preset will remove all gear except that one item.
> This means that any time you try to edit a preset you need to add every single item seperately as it creatiny a new preset

this is a already made topic. but nevertheless you are right

_Originally posted by @TitanGH in https://github.com/oldschoolgg/oldschoolbot/issues/4411

**Comment by nwjgit** [comment] 2024-09-02 19:42
dupe of https://github.com/oldschoolgg/oldschoolbot/issues/4411

**Closed by nwjgit** 2024-09-02 19:42 UTC
