### ISSUE TITLE
=monster on bso is wrong attempt #3

### ISSUE THREAD

**Issue by wyattos** [oldschoolgg/oldschoolbot#680] opened 2020-09-24 00:44 UTC
"figure it out" -alex responding to me whenever i ask a question in developers

**Comment by Alexsuperfly** [comment] 2020-09-24 00:44
duplicate of #678

**Comment by wyattos** [comment] 2020-09-24 00:44
ill make another issue later when you go to bed so it doesnt get closed, no worries

**Closed by Alexsuperfly** 2020-09-24 00:44 UTC

**Comment by osrsolympus** [comment] 2020-09-24 01:11
Also just to be clear it’s a dupe of #554. If you guys are gonna have your pissing matches in GitHub at least do it properly.

**Comment by Alexsuperfly** [comment] 2020-09-24 01:12
ahh yes, ty i wouldn't have known because i had no information to go off of

**Comment by wyattos** [comment] 2020-09-24 01:13
> Also just to be clear it’s a dupe of #554. If you guys are gonna have your pissing matches in GitHub at least do it properly.

maybe if i was told that instead of the 12 year old closing my issues i wouldve only made one
