### ISSUE TITLE
Buyable bloodrunes

### ISSUE THREAD

**Issue by RaveOsrs** [oldschoolgg/oldschoolbot#3385] opened 2022-01-03 21:08 UTC
## 🚀 Buyable bloodrunes
The meta to get blood runes for ironman in the original game is to buy them from shops.
Since scythe is added now, can u make blood runes buyable?

**Comment by 6enny6** [comment] 2022-01-03 21:12
dupe of #3369

**Closed by 6enny6** 2022-01-03 21:12 UTC
