### ISSUE TITLE
Typo on fletching

### ISSUE THREAD

**Issue by Oppheng** [oldschoolgg/oldschoolbot#1340] opened 2021-02-10 23:22 UTC
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

This is more of a typo then bug with the discord bot itself.
**The typos are highlighted with** **bold text**

*When doing the command: +fletch ruby bolt tips
This is what pop up when the minion arrives back*
....... **finished fletching 8856 s**, you also received 4,649.4 XP.
Say ‍y‎ to repeat this trip.

*With dragon bolts:
+fletch dragon bolts*
....is now Fletching 20000 x Dragon **boltss**, it'll take around 40 minutes to finish.

When minion arrives back home
....finished fletching __**20000 s**__, you also received 240,000 XP.

**Comment by osrsolympus** [comment] 2021-02-10 23:36
Duplicate of #1302 which is itself a duplicate of #1293

**Closed** 2021-02-10 23:38 UTC
