### ISSUE TITLE
Cl sea kraken displays wrong image

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#1640] opened 2021-04-03 19:23 UTC
##  🐛 Bug report

=Cl sea kraken shows the cl for zil

![file](https://user-images.githubusercontent.com/77698878/113489137-07aa5a80-9488-11eb-8773-8958b6deff76.jpg)

![file](https://user-images.githubusercontent.com/77698878/113489141-0e38d200-9488-11eb-821d-2ea154e38737.jpg)

**Comment by TizHub** [comment] 2021-04-03 19:23
duplicate of #1170 can be closed

**Closed** 2021-04-03 19:24 UTC
