### ISSUE TITLE
Osb Clue (image?) bug 

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#1703] opened 2021-04-16 17:36 UTC
Loot shows 2 clue scrolls 
![55DC4EF5-71DB-4430-BB4C-BD8C8D603B99](https://user-images.githubusercontent.com/68600561/115062745-87302480-9e9f-11eb-9335-6e2b87c45698.png)

**Comment by osrsolympus** [comment] 2021-04-16 17:38
Duplicate of #1646

**Closed by osrsolympus** 2021-04-16 17:38 UTC
