### ISSUE TITLE
OSB ONLY: Page #4 on Runecraft LB won't load.

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1744] opened 2021-04-26 11:53 UTC
## 🐛 Bug Report

https://i.imgur.com/BzxPl0o.gifv

only seems to be Runecraft LB and on OSB

**Comment by thievious1** [comment] 2021-04-26 13:41
duplicate of #1679

**Closed by thievious1** 2021-04-26 13:41 UTC
