### ISSUE TITLE
Hard Clue Collection Log

### ISSUE THREAD

**Issue by Keyzz971** [oldschoolgg/oldschoolbot#610] opened 2020-09-07 14:13 UTC
On the hard clue collection log on both OSB and BSO there is the item “Pirate’s Hat” added onto the log next to the selection of cavaliers but you can’t actually obtain this item from hard clue scrolls or any other type of clue scroll.

**Comment by kevinsmendes** [comment] 2020-09-07 14:14
Duplicate of #508

**Closed** 2020-09-07 14:26 UTC
