### ISSUE TITLE
Nightmare Collection Log Dupe

### ISSUE THREAD

**Issue by TwiceUponATaco** [oldschoolgg/oldschoolbot#854] opened 2020-10-08 18:53 UTC
## 🐛 Bug Report

Taking apart a nightmare staff with orb adds a staff and orb to your collection log. This can be repeated endlessly like the verac's set was doing a few months ago.

**Comment by ard35** [comment] 2020-10-08 18:55
Duplicate of #853 so I will close this one. The added information of the relation to a previous issue is a good addition though.

**Closed by ard35** 2020-10-08 18:55 UTC
Labels: duplicate
