### ISSUE TITLE
(BSO) Make Zamorakian Hasta Count for Cerb requirement (as that's what it's used for)

### ISSUE THREAD

**Issue by swahsam** [oldschoolgg/oldschoolbot#798] opened 2020-10-03 03:03 UTC
(BSO) Make Zamorakian Hasta Count for Cerb requirement (as that's what it's used for)

(CERB IS NOT THE SAME AS CORP)

**Comment by Alexsuperfly** [comment] 2020-10-03 03:04
duplicate of #797

**Closed by Alexsuperfly** 2020-10-03 03:04 UTC
