### ISSUE TITLE
Can't do cl for missing items in text format

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4592] opened 2022-10-13 03:49 UTC
## 🚀 Feature Proposal

i am hardcore missing the feature that showed missing cl items in text format.

without it, I'm having trouble finding out what this new item is on misc cl.

![SmartSelect_20221012_223837_Discord.jpg](https://media.discordapp.net/attachments/736774315403509791/1029963618009231460/collection_log_1665632862048.png)

**Comment by LuxrayElite** [comment] 2022-10-13 07:54
dupe of https://github.com/oldschoolgg/oldschoolbot/issues/4381
No idea on the item

**Closed** 2022-10-13 08:07 UTC

**Comment by TURB042O** [comment] 2022-10-18 20:28
> dupe of #4381 No idea on the item

item is ivy seed I found out. from treebeard
