### ISSUE TITLE
Masses and Combat XP

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1569] opened 2021-03-20 23:26 UTC
## 🐛 Bug Report

Masses give too much combat xp or something fishy has the details

**Comment by Alexsuperfly** [comment] 2021-03-20 23:28
duplicate of #1564

**Comment by osrsolympus** [comment] 2021-03-20 23:29
it’s all masses not just nightmare

**Comment by Alexsuperfly** [comment] 2021-03-20 23:30
i am aware, it doesnt change the fact that this is the same issue as the other one

**Closed by Alexsuperfly** 2021-03-20 23:30 UTC
