### ISSUE TITLE
Add menaphite remedy to herblore

### ISSUE THREAD

**Issue by J4stMart** [oldschoolgg/oldschoolbot#5418] opened 2023-10-09 08:41 UTC
## 🚀 Feature Proposal

Add the possibility to create [menaphite remedy](https://oldschool.runescape.wiki/w/Menaphite_remedy#4_dose) potions for the herblore xp. We already have the lily of the sands drop through toa.

**Comment by TastyPumPum** [comment] 2023-10-09 08:41
Duplicate of #4951

**Closed by TastyPumPum** 2023-10-09 08:41 UTC
