### ISSUE TITLE
Necromancer robe top & robe bottom - sprites are incorrectly switched around

### ISSUE THREAD

**Issue by erichmond2** [oldschoolgg/oldschoolbot#5453] opened 2023-10-23 05:40 UTC
Pretty much the necromancer robe top and bottom's sprites are switched, as the bottoms show as the top (in the leg slot) and the top shows the bottoms (in the chest slot).

**Comment by nwjgit** [comment] 2023-12-17 04:06
dupe of: https://github.com/oldschoolgg/oldschoolbot/issues/4852

**Closed by nwjgit** 2023-12-17 04:06 UTC
