### ISSUE TITLE
Zippy CL

### ISSUE THREAD

**Issue by SDRadford** [oldschoolgg/oldschoolbot#1555] opened 2021-03-18 18:22 UTC
## 🐛 Bug Report

There's a report on Zippy not showing up from being before the pets CL but I got a zippy just the other day and its not shown up on my CL, yet one of my CC mates has zippy unlocked on his. Also checking the mostdrops it says one person has over 400 and another over 80, are drops going towards them somehow? Or is that left over dice banking mischief?

**Comment by mylife212** [comment] 2021-03-18 18:34
Regarding the bit about mostdrops: There was a bug with hunter where hunting ferrets actually gave zippy (due to same ID), so the mostdrops list got skewed. Zippys aren't going towards anyone else!

**Comment by AvariceBrah** [comment] 2021-03-18 20:44
I got zippy at 18 qp yesterday on my ironman?

**Comment by osrsolympus** [comment] 2021-03-18 20:55
> I got zippy at 18 qp yesterday on my ironman?

This is not what the issue is about. In the future, please take care to make sure your comments are productive and not clogging up the issue thread.

**Comment by AvariceBrah** [comment] 2021-03-18 23:31
What's the context then? As worded, I don't understand, I guess? 
Just handed info that seemed to contradict the claim. Apologies.
>Zippys aren't going towards anyone else!

**Comment by mylife212** [comment] 2021-03-19 18:43
The context here isn't that Zippy not dropping, we know it is dropping correctly. The issue is that its not being added to the collection log (Or rather, being inconsistently added. IE: SDRad got a zippy and it didn't count towards log, but his buddies zippy did count). Is Zippy in your =cl pets?

**Comment by themrrobert** [comment] 2021-03-21 03:46
I just got Zippy on ironman, and it does not appear in the collection log.

Neither does my Wilvus, but I don't even a placeholder for Wilvus

**Comment by gc** [comment] 2023-10-20 07:01
I believe this is fixed now.

**Closed by gc** 2023-10-20 07:01 UTC
